### PR TITLE
Feature: Add Russian translation to Rebound Run

### LINKED ISSUE #33: Bug: Lenovo is shown to be the developer of Rebound
### 🪟 What OS build is this issue present?

_Coming soon!_

### 🔢 What version are you on?

_Coming soon!_

### 📄 Description

_Coming soon!_

### 🪜 Steps To Reproduce

_Coming soon!_

### 🤔 Expected behavior

_Coming soon!_

### Affected platforms

🪟 Windows

### ⚒️ Did you find any workaround?

_Coming soon!_

### 📸 Assets

_Coming soon!_

### PR DESCRIPTION
**Pull request by ke46138**
### Changes:

- Added Russian translation to Rebound run
- Fixed null strings in translation in Rebound run, if translation not supported. Default language is English.
- Optimized translation selection (using switch case instead of if else) in Rebound run

Sorry for my English, I use a translator.

### CODE REVIEW

**Comment by Lamparter** [comment]
Thank you for your contribution @ke46138!

Is there anything else you'd like to do before merge? If so, I'll mark this pull request as a draft.

**Comment by Lamparter** [comment]
@IviriusMain do you think I should move the strings to Rebound.Delivery? This would allow for a unified place to localise the app and no strings would be duplicated.

**Comment by ke46138** [comment]
> Thank you for your contribution @ke46138!
> 
> Is there anything else you'd like to do before merge? If so, I'll mark this pull request as a draft.

No

**Review by Lamparter — APPROVED** [review]
LGTM

**Comment by Lamparter** [comment]
@ke46138 thank you so much for your contribution!

**Pull request merged**
